spring:
  application:
    name: springboot-with-rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    topic-exchange-name: "sent-message"
    queue-name: "message.notification"
