name: Spring boot Continuos Integration

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Display Docker Version
        run: docker --version
      - name: Run Tests
        env:
          TESTCONTAINERS_RYUK_DISABLED: 'true'
        run: mvn test